# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Mohammad Hakim Blog
first_name: Mohammad
last_name: Hakim
contact_note: You can contact me here.
description: My personal GitHub Pages blog
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>.
keywords: jekyll, github-pages, blog
lang: en
icon: ⚛️

url: https://mohammadhakim73.github.io
baseurl: "" # root
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true

max_width: 930px

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: My Blog
blog_description: A simple academic-style blog
permalink: /blog/:year/:title/

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude: ["bin/", "vendor"]
keep_files: [CNAME, .nojekyll]

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

# -----------------------------------------------------------------------------
# Optional features
# -----------------------------------------------------------------------------
enable_darkmode: true
enable_math: true
enable_masonry: true

